{% set version = "3.1.7" %}

package:
  name: gplite
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/gplite/gplite-{{ version }}.tar.gz
  sha256: 13fb6d2f430e0f24ab0ff10b8f18ea6b085b4d80274b88f77189e6ef4bc0acba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24
    - scipy >=1.10.0

test:
  imports:
    - gplite
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/gplite/
  summary: Lightweight Gaussian Process regression library
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - soconnor16
