{% set version = "3.2.0" %}

package:
  name: gplite
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/gplite/gplite-{{ version }}.tar.gz
  sha256: 989e928d5185f8b617566e74ab609cbbd8c5adbe27379f2cb69ed0f9e62e932c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24
    - scipy >=1.10.0

test:
  imports:
    - gplite
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/gplite/
  summary: Lightweight Gaussian Process regression library
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - soconnor16
